### ISSUE TITLE
[Bug] Deleted Conversations Retained 

### ISSUE THREAD

**Issue by QwopJoans** [sgtaziz/WebMessage#35] opened 2021-02-10 01:06 UTC
If you delete a conversation in iMessage, the conversation doesn't disappear from the WebMessage app unless the settings are saved to force a reload. Additionally, if a new message is received from someone in a deleted conversation, the messages that were deleted but were loaded into WebMessage previously are displayed.

**Comment by sgtaziz** [comment] 2021-02-11 05:14
Unfortunately this is a known logic, though not a bug. Hooking deleting threads isn't currently supported, but will be supported once I add the ability to delete threads within WebMessage

**Comment by sgtaziz** [comment] 2021-02-13 17:15
Reopening this to track it, since deleting threads is now supported

**Comment by sgtaziz** [comment] 2021-02-19 13:08
Fixed with 2779e80

**Closed by sgtaziz** 2021-02-19 13:08 UTC
Labels: bug
