### ISSUE TITLE
Couldnt be use when device sleeps

### ISSUE THREAD

**Issue by symbuzzer** [sgtaziz/WebMessage#17] opened 2021-01-30 13:31 UTC
probably because ssh generic bug

**Comment by sgtaziz** [comment] 2021-01-30 14:30
What do you mean by this? If the screen is off it still works on my end. SSH is not used here so it shouldn't be related

**Comment by gnawh** [comment] 2021-01-30 20:10
After awhile, the connection will be lost and won't work until you wake your phone. I think it's caused by the wi-fi being idle, or not being fully connected. Fiona or iNoSleep used to fix these types of issues. This is just my speculation, and I ended up installing iNoSleep to see if it works (don't even know if it's compiled for my device properly). It'd be cool if this always awake could be built it as an option. Whenever I "lose" connection (conversations stop loading), I use Hey Siri and it connects again.

**Comment by sgtaziz** [comment] 2021-01-31 13:55
Strange. I'll have to look into it and will keep you posted. Thanks!

**Comment by sgtaziz** [comment] 2021-02-06 10:33
I was told this issue no longer exists with the latest Tweak update. Can one of you guys confirm this?

**Comment by sgtaziz** [comment] 2021-02-06 10:33
I was told this issue no longer exists with the latest Tweak update. Can one of you guys confirm this? @gnawh @symbuzzer

**Comment by gnawh** [comment] 2021-02-06 10:34
I'll definitely keep an eye out and disable inosleep.

**Comment by sgtaziz** [comment] 2021-02-11 12:08
I will close this for now. Feel free to open another issue if it happens again 👍

**Closed by sgtaziz** 2021-02-11 12:08 UTC
Labels: bug

**Comment by sgtaziz** [comment] 2021-02-27 06:42
@symbuzzer @astra-io 

If you guys experience this issue again, I found the cause. When using unc0ver, there is an option to "Disable Auto Updates". When enabled, it will put your WiFi in a deep sleep mode when locked, and prevents WebMessage from functioning correctly. I recommend disabling this and using a profile to disable auto updates if needed instead.
